### ISSUE TITLE
Test OAuth flow for Dropbox

### ISSUE THREAD

**Issue by anxuae** [pibooth/pibooth-dropbox#3]
Hi @mhilcher,

I've introduce the token generation applying OAuth2 flow. Code is inspired from google one.
In the config you now only need the app_key and app_secret.
Also, I've added a tuto in the README.

Can you test it on your environment?

**Comment by mhilcher** [comment]
Sure, I will test it.
Do I need to create a google app for this?
Because they closed my developer account due to I did not refresh my invoice settings :)


Am 25. April 2022 12:29:17 MESZ schrieb Anxuae ***@***.***>:
>Hi @mhilcher,
>
>I've introduce the token generation applying OAuth2 flow. Code is inspired from google one.
>In the config you now only need the app_key and app_secret.
>Also, I've added a tuto in the README.
>
>Can you test it on your environment?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pibooth/pibooth-dropbox/issues/3
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by anxuae** [comment]
No, you don't need google. Just update the plugin by doing those commands in the directory where you have cloned the **pibooth-dropbox** plugin.
It will install the "developing" version of the plugin.

```
git pull
pip3 install -e .
```

then run pibooth (update config key names if necessary)

**Comment by mhilcher** [comment]
Ok, now I see, I read the message on the fly on my mobile this afternoon and I didn't read it correctly.
Ok, I see the changes now, they are huge, and I will try it with another dropbox account of mine, which has no app created so far.
So I will start from the ground with the new version and will report if it works.

For me now it is night, I am going to test this tomorrow.

**Comment by mhilcher** [comment]
Ok, I tested.

I created a new app and set the global scope and the scope rights.
First failed, because I did not set the redirect url, so I stopped this, set the url and restarted.

The authentication website shows up and after I allow pibooth to use the app pibooth shows up and I can take pictures.

But the picture is not uploaded because of the wrong scope rights. So I looked into the app and all rights that I gave to the app where gone. After setting the rights again the upload still fails because pibooth already has a token, but with the wrong rights.

Maybe I did not save the scope rights correctly when creating the app, I don't know.
But now I have this token and I don't know how to reset it. There is no token in the config file that I can delete before starting the whole authentication part again.

From my point of view there has to be an option to restart the oauth2 process if someone makes the same mistake as I did.

And another thing: If the picture can not be uploaded the the whole process stops working and the picture is not processed.
As the dropbox upload is not essential for the final picture processing there has to be an exception which allows to continue with the processing. The qr code would be not usable, but the picture can still be shown and printed.

**Comment by anxuae** [comment]
Thanks for your feedback, I will fix it and tell you when it is ready

**Comment by anxuae** [comment]
v0.0.3 published, if you have time to test

**Comment by mhilcher** [comment]
Hi,

first test worked as designed. I double checked that all rights and the redirect url where set correctly in the dropbox app.
After the authentication the pictures where uploaded to my dropbox folder.

Next test: I'm gonna make an error by setting the wrong rights and will see, what happens when the upload fails.
But I don't yet know when I will have time for that.

One Question: Where is the refresh token stored, it's still not visible in the config.

**Comment by anxuae** [comment]
Token is stored in the file `~/.config/pibooth/.dropbox_token.json`

**Comment by anxuae** [comment]
Closed, please re-open if you encounter any error
